export { default as Create } from './Create'
export { default as Delete } from './Delete'
export { default as Edit } from './Edit'
export { default as List } from './List'
export { default as Show } from './Show'
